import { PrismaClient, ExerciseType } from '@prisma/client'

const prisma = new PrismaClient()

const exercises = [
  {
    name: "Press de banca plano",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Pecho",
    equipment: "Barra",
    tags: ["press", "pecho", "compound"],
    description: "Ejercicio de pecho tipo strength. Requiere barra.",
    clientDescription: "Acostado boca arriba en un banco plano, agarrá la barra con las manos un poco más anchas que los hombros. Bajá la barra controladamente hasta tocar el pecho y empujá hacia arriba hasta extender los brazos.",
    isPublic: true,
  },
  {
    name: "Press de banca inclinado",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Pecho",
    equipment: "Barra",
    tags: ["press", "pecho", "inclinado"],
    description: "Ejercicio de pecho tipo strength. Requiere barra.",
    clientDescription: "Igual que el press plano pero en un banco inclinado entre 30° y 45°. Enfoca más la parte superior del pecho y los hombros.",
    isPublic: true,
  },
  {
    name: "Press de banca declinado",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Pecho",
    equipment: "Barra",
    tags: ["press", "pecho", "declinado"],
    description: "Ejercicio de pecho tipo strength. Requiere barra.",
    clientDescription: "Acostado en banco declinado (pies arriba), empujá la barra desde el pecho inferior. Trabaja más la parte baja del pecho.",
    isPublic: true,
  },
  {
    name: "Aperturas con mancuernas",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Pecho",
    equipment: "Mancuernas",
    tags: ["aperturas", "pecho", "aislado"],
    description: "Ejercicio de pecho tipo strength. Requiere mancuernas.",
    clientDescription: "Acostado en banco plano con mancuernas extendidas sobre el pecho. Abrí los brazos lateralmente en arco hasta sentir el estiramiento y volvé al centro.",
    isPublic: true,
  },
  {
    name: "Cruces en polea",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Pecho",
    equipment: "Polea",
    tags: ["cruces", "pecho", "aislado"],
    description: "Ejercicio de pecho tipo strength. Requiere polea.",
    clientDescription: "De pie en el centro de dos poleas altas, tirá las manos hacia abajo y adelante cruzándolas frente al pecho. Mantené los codos ligeramente flexionados.",
    isPublic: true,
  },
  {
    name: "Fondos en paralelas",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Pecho",
    equipment: "Paralelas",
    tags: ["fondos", "pecho", "compound"],
    description: "Ejercicio de pecho tipo strength. Requiere paralelas.",
    clientDescription: "Colgado de las paralelas con los codos extendidos, inclinate un poco hacia adelante y bajá flexionando los codos hasta que los hombros queden por debajo de los codos. Subí empujando.",
    isPublic: true,
  },
  {
    name: "Pull-over",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Pecho",
    equipment: "Mancuerna",
    tags: ["pullover", "pecho", "aislado"],
    description: "Ejercicio de pecho tipo strength. Requiere mancuerna.",
    clientDescription: "Acostado en banco plano con una mancuerna sostenida con ambas manos sobre el pecho. Bajá la mancuerna en arco por detrás de la cabeza estirando los brazos y volvé al centro.",
    isPublic: true,
  },
  {
    name: "Dominadas",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Barra",
    tags: ["dominadas", "espalda", "compound"],
    description: "Ejercicio de espalda tipo strength. Requiere barra.",
    clientDescription: "Colgado de una barra con las palmas hacia afuera (agarre prono), tirá de tu cuerpo hacia arriba hasta que la barbilla supere la barra. Bajá controladamente.",
    isPublic: true,
  },
  {
    name: "Jalón al pecho",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Polea",
    tags: ["jalon", "espalda", "compound"],
    description: "Ejercicio de espalda tipo strength. Requiere polea.",
    clientDescription: "Sentado en la máquina de polea alta, agarrá la barra con las manos más anchas que los hombros. Tirá la barra hacia abajo hasta la parte superior del pecho, apretando los omóplatos.",
    isPublic: true,
  },
  {
    name: "Remo con barra",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Barra",
    tags: ["remo", "espalda", "compound"],
    description: "Ejercicio de espalda tipo strength. Requiere barra.",
    clientDescription: "Inclinado hacia adelante con la espalda recta y la barra colgando, tirá la barra hacia tu abdomen inferior apretando los omóplatos juntos.",
    isPublic: true,
  },
  {
    name: "Remo con mancuerna",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Mancuerna",
    tags: ["remo", "espalda", "unilateral"],
    description: "Ejercicio de espalda tipo strength. Requiere mancuerna.",
    clientDescription: "Apoyá una mano y la rodilla del mismo lado en un banco, con la otra mano tirá la mancuerna hacia tu cadera apretando el omóplato.",
    isPublic: true,
  },
  {
    name: "Remo en máquina",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Máquina",
    tags: ["remo", "espalda", "maquina"],
    description: "Ejercicio de espalda tipo strength. Requiere máquina.",
    clientDescription: "Sentado en la máquina con el pecho apoyado en el soporte, tirá las manijas hacia atrás apretando los omóplatos. Mantené los codos cerca del cuerpo.",
    isPublic: true,
  },
  {
    name: "Peso muerto",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Barra",
    tags: ["peso muerto", "espalda", "compound"],
    description: "Ejercicio de espalda tipo strength. Requiere barra.",
    clientDescription: "De pie con la barra frente a los pies, inclinate hacia adelante manteniendo la espalda recta y levantá la barra extendiendo caderas y rodillas al mismo tiempo.",
    isPublic: true,
  },
  {
    name: "Hiperextensiones",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Banco",
    tags: ["hiperextensiones", "espalda baja", "aislado"],
    description: "Ejercicio de espalda tipo strength. Requiere banco.",
    clientDescription: "Acostado boca abajo en el banco de hiperextensiones con las caderas en el borde, bajá el torso hacia abajo y levantalo extendiendo la espalda baja.",
    isPublic: true,
  },
  {
    name: "Press militar",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Barra",
    tags: ["press", "hombros", "compound"],
    description: "Ejercicio de hombros tipo strength. Requiere barra.",
    clientDescription: "De pie o sentado con la barra a la altura de los hombros, empujá la barra hacia arriba hasta extender completamente los brazos. Bajá controladamente.",
    isPublic: true,
  },
  {
    name: "Press con mancuernas",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Mancuernas",
    tags: ["press", "hombros", "compound"],
    description: "Ejercicio de hombros tipo strength. Requiere mancuernas.",
    clientDescription: "Sentado con mancuernas a la altura de los hombros, empujá hacia arriba hasta que las mancuernas casi se toquen. Bajá controladamente.",
    isPublic: true,
  },
  {
    name: "Elevaciones laterales",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Mancuernas",
    tags: ["elevaciones", "hombros", "aislado"],
    description: "Ejercicio de hombros tipo strength. Requiere mancuernas.",
    clientDescription: "De pie con mancuernas a los costados, elevá los brazos lateralmente hasta la altura de los hombros. Bajá lentamente. Mantené un leve flexión en los codos.",
    isPublic: true,
  },
  {
    name: "Elevaciones frontales",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Mancuernas",
    tags: ["elevaciones", "hombros", "aislado"],
    description: "Ejercicio de hombros tipo strength. Requiere mancuernas.",
    clientDescription: "De pie con mancuernas frente a los muslos, elevá un brazo hacia adelante hasta la altura del hombro. Bajá y alterná con el otro brazo.",
    isPublic: true,
  },
  {
    name: "Pájaro",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Mancuernas",
    tags: ["pajaro", "hombros", "posterior"],
    description: "Ejercicio de hombros tipo strength. Requiere mancuernas.",
    clientDescription: "Inclinado hacia adelante con el torso casi paralelo al piso, elevá las mancuernas lateralmente con los codos ligeramente flexionados. Apretá los omóplatos.",
    isPublic: true,
  },
  {
    name: "Face pull",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Polea",
    tags: ["face pull", "hombros", "posterior"],
    description: "Ejercicio de hombros tipo strength. Requiere polea.",
    clientDescription: "Con la polea a la altura de la cara y una cuerda, tirá hacia tu cara separando los codos y llevándolos hacia atrás. Apretá los omóplatos al final.",
    isPublic: true,
  },
  {
    name: "Curl con barra",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Bíceps",
    equipment: "Barra",
    tags: ["curl", "biceps", "aislado"],
    description: "Ejercicio de bíceps tipo strength. Requiere barra.",
    clientDescription: "De pie con la barra frente a los muslos, flexioná los codos llevando la barra hacia los hombros. Bajá controladamente sin dejar que los codos se muevan.",
    isPublic: true,
  },
  {
    name: "Curl con mancuernas",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Bíceps",
    equipment: "Mancuernas",
    tags: ["curl", "biceps", "aislado"],
    description: "Ejercicio de bíceps tipo strength. Requiere mancuernas.",
    clientDescription: "De pie con mancuernas a los costados, flexioná los codos alternando brazos. Mantené los codos pegados al cuerpo.",
    isPublic: true,
  },
  {
    name: "Curl martillo",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Bíceps",
    equipment: "Mancuernas",
    tags: ["curl", "biceps", "martillo"],
    description: "Ejercicio de bíceps tipo strength. Requiere mancuernas.",
    clientDescription: "Igual que el curl con mancuernas pero con las palmas mirando hacia adentro (agarre neutro). Trabaja más el braquial.",
    isPublic: true,
  },
  {
    name: "Curl en predicador",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Bíceps",
    equipment: "Barra",
    tags: ["curl", "biceps", "predicador"],
    description: "Ejercicio de bíceps tipo strength. Requiere barra.",
    clientDescription: "Sentado en el banco predicador con los brazos apoyados en la almohadilla, flexioná los codos llevando la barra hacia los hombros. Bajá hasta extender casi por completo.",
    isPublic: true,
  },
  {
    name: "Curl concentrado",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Bíceps",
    equipment: "Mancuerna",
    tags: ["curl", "biceps", "concentrado"],
    description: "Ejercicio de bíceps tipo strength. Requiere mancuerna.",
    clientDescription: "Sentado en un banco con las piernas abiertas, apoyá el codo en el interior del muslo y flexioná la mancuerna hacia el hombro. Bajá lentamente.",
    isPublic: true,
  },
  {
    name: "Press francés",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Tríceps",
    equipment: "Barra",
    tags: ["press frances", "triceps", "aislado"],
    description: "Ejercicio de tríceps tipo strength. Requiere barra.",
    clientDescription: "Acostado en banco plano con la barra sostenida sobre el pecho, bajá la barra hacia la frente flexionando solo los codos. Extendé los brazos para volver.",
    isPublic: true,
  },
  {
    name: "Extensiones en polea",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Tríceps",
    equipment: "Polea",
    tags: ["extensiones", "triceps", "aislado"],
    description: "Ejercicio de tríceps tipo strength. Requiere polea.",
    clientDescription: "Con la polea alta y una cuerda o barra, flexioná los codos llevando las manos hacia la frente y luego extendé hacia abajo apretando los tríceps.",
    isPublic: true,
  },
  {
    name: "Fondos",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Tríceps",
    equipment: "Paralelas",
    tags: ["fondos", "triceps", "compound"],
    description: "Ejercicio de tríceps tipo strength. Requiere paralelas.",
    clientDescription: "Colgado de las paralelas con el torso vertical, bajá flexionando los codos hasta que los hombros estén por debajo. Subí empujando con los tríceps.",
    isPublic: true,
  },
  {
    name: "Patada de tríceps",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Tríceps",
    equipment: "Mancuerna",
    tags: ["patada", "triceps", "aislado"],
    description: "Ejercicio de tríceps tipo strength. Requiere mancuerna.",
    clientDescription: "Inclinado hacia adelante con una mancuerna en la mano, llevá el codo hacia arriba y extendé el brazo hacia atrás apretando el tríceps. Bajá lentamente.",
    isPublic: true,
  },
  {
    name: "Sentadilla",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Cuádriceps",
    equipment: "Barra",
    tags: ["sentadilla", "piernas", "compound"],
    description: "Ejercicio de cuádriceps tipo strength. Requiere barra.",
    clientDescription: "Con la barra sobre los trapecios, bajá flexionando rodillas y caderas hasta que los muslos estén paralelos al suelo. Mantené la espalda recta y subí empujando con los talones.",
    isPublic: true,
  },
  {
    name: "Sentadilla frontal",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Cuádriceps",
    equipment: "Barra",
    tags: ["sentadilla", "piernas", "frontal"],
    description: "Ejercicio de cuádriceps tipo strength. Requiere barra.",
    clientDescription: "Con la barra apoyada en los hombros delante del cuello (agarre de clean), bajá en sentadilla manteniendo el torso más vertical. Enfoca más los cuádriceps.",
    isPublic: true,
  },
  {
    name: "Prensa",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Cuádriceps",
    equipment: "Máquina",
    tags: ["prensa", "piernas", "compound"],
    description: "Ejercicio de cuádriceps tipo strength. Requiere máquina.",
    clientDescription: "Sentado en la máquina de prensa con los pies en la plataforma a la altura de los hombros, empujá extendiendo las piernas sin bloquear las rodillas. Bajá controladamente.",
    isPublic: true,
  },
  {
    name: "Extensión de cuádriceps",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Cuádriceps",
    equipment: "Máquina",
    tags: ["extensiones", "cuadriceps", "aislado"],
    description: "Ejercicio de cuádriceps tipo strength. Requiere máquina.",
    clientDescription: "Sentado en la máquina con los tobillos debajo del rodillo, extendé las rodillas hasta enderezar las piernas. Bajá lentamente sin dejar que el peso toque.",
    isPublic: true,
  },
  {
    name: "Curl femoral",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Femoral",
    equipment: "Máquina",
    tags: ["curl", "femoral", "aislado"],
    description: "Ejercicio de femoral tipo strength. Requiere máquina.",
    clientDescription: "Acostado boca abajo en la máquina con los talones debajo del rodillo, flexioná las rodillas llevando los talones hacia los glúteos. Bajá controladamente.",
    isPublic: true,
  },
  {
    name: "Peso muerto rumano",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Femoral",
    equipment: "Barra",
    tags: ["peso muerto", "femoral", "rumano"],
    description: "Ejercicio de femoral tipo strength. Requiere barra.",
    clientDescription: "De pie con la barra frente a los muslos, inclinate hacia adelante desde las caderas manteniendo las piernas casi rectas y la espalda recta. Bajá hasta sentir el estiramiento en los isquiotibiales.",
    isPublic: true,
  },
  {
    name: "Hip thrust",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Glúteos",
    equipment: "Barra",
    tags: ["hip thrust", "gluteos", "compound"],
    description: "Ejercicio de glúteos tipo strength. Requiere barra.",
    clientDescription: "Con la espalda apoyada en un banco y la barra sobre las caderas, empujá las caderas hacia arriba apretando los glúteos hasta que el torso quede paralelo al piso. Bajá controladamente.",
    isPublic: true,
  },
  {
    name: "Elevación de talones",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Pantorrilla",
    equipment: "Máquina",
    tags: ["elevacion", "pantorrilla", "aislado"],
    description: "Ejercicio de pantorrilla tipo strength. Requiere máquina.",
    clientDescription: "De pie en la máquina de pantorrillas con los hombros bajo el soporte, subí los talones lo más alto posible apretando las pantorrillas. Bajá hasta sentir el estiramiento.",
    isPublic: true,
  },
  {
    name: "Plancha",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Peso corporal",
    tags: ["plancha", "core", "isometrico"],
    description: "Ejercicio de core tipo strength. Requiere peso corporal.",
    clientDescription: "Apoyado en antebrazos y puntas de los pies, mantené el cuerpo en línea recta desde la cabeza hasta los talones. Contraé el abdomen y las nalgas. Mantené la posición.",
    isPublic: true,
  },
  {
    name: "Crunch",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Peso corporal",
    tags: ["crunch", "abdominales", "aislado"],
    description: "Ejercicio de core tipo strength. Requiere peso corporal.",
    clientDescription: "Acostado boca arriba con rodillas flexionadas y pies en el suelo, elevá los hombros del suelo contrayendo el abdomen. No tires del cuello. Bajá lentamente.",
    isPublic: true,
  },
  {
    name: "Elevación de piernas",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Banco",
    tags: ["elevacion", "abdominales", "aislado"],
    description: "Ejercicio de core tipo strength. Requiere banco.",
    clientDescription: "Acostado en un banco plano, agarrá el borde del banco y elevá las piernas rectas hacia arriba hasta formar un ángulo de 90° con el torso. Bajá controladamente.",
    isPublic: true,
  },
  {
    name: "Russian twist",
    type: "STRENGTH" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Peso corporal",
    tags: ["russian twist", "oblicuos", "aislado"],
    description: "Ejercicio de core tipo strength. Requiere peso corporal.",
    clientDescription: "Sentado en el suelo con las piernas flexionadas y elevadas, inclinate ligeramente hacia atrás y girá el torso de un lado al otro tocando el suelo a cada lado.",
    isPublic: true,
  },
  {
    name: "Caminata en cinta",
    type: "CARDIO" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Cinta",
    tags: ["cardio", "cinta", "bajo impacto"],
    description: "Ejercicio de full body tipo cardio. Requiere cinta.",
    clientDescription: "Caminá sobre la cinta a un ritmo cómodo. Mantené la espalda recta y los brazos balanceándose naturalmente. Ajustá la velocidad e inclinación según tu nivel.",
    isPublic: true,
  },
  {
    name: "Carrera en cinta",
    type: "CARDIO" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Cinta",
    tags: ["cardio", "cinta", "running"],
    description: "Ejercicio de full body tipo cardio. Requiere cinta.",
    clientDescription: "Corré sobre la cinta a un ritmo constante. Mantené una zancada natural y los brazos flexionados a 90°. Ajustá velocidad e inclinación progresivamente.",
    isPublic: true,
  },
  {
    name: "Elíptica",
    type: "CARDIO" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Elíptica",
    tags: ["cardio", "eliptica", "bajo impacto"],
    description: "Ejercicio de full body tipo cardio. Requiere elíptica.",
    clientDescription: "Sobre la elíptica, mové brazos y piernas en sincronía. Mantené la espalda recta, el core activado y una cadencia constante.",
    isPublic: true,
  },
  {
    name: "Bicicleta estática",
    type: "CARDIO" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Bicicleta",
    tags: ["cardio", "bicicleta", "bajo impacto"],
    description: "Ejercicio de piernas tipo cardio. Requiere bicicleta.",
    clientDescription: "Pedaleá sobre la bicicleta estática manteniendo una cadencia constante. Ajustá la resistencia según tu nivel. Mantené la espalda apoyada en el respaldo.",
    isPublic: true,
  },
  {
    name: "Remo",
    type: "CARDIO" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Remo",
    tags: ["cardio", "remo", "full body"],
    description: "Ejercicio de full body tipo cardio. Requiere remo.",
    clientDescription: "Sentado en la máquina de remo, agarrá el mango con ambas manos. Extendé las piernas y tirá el mango hacia ti llevando los codos atrás. Volvé controladamente.",
    isPublic: true,
  },
  {
    name: "Saltar la soga",
    type: "CARDIO" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Soga",
    tags: ["cardio", "soga", "plyometrico"],
    description: "Ejercicio de full body tipo cardio. Requiere soga.",
    clientDescription: "Con la soga detrás de los pies, saltá sobre ella girando las muñecas. Mantené los codos cerca del cuerpo y saltá solo lo necesario para pasar la soga.",
    isPublic: true,
  },
  {
    name: "Burpees",
    type: "CARDIO" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Peso corporal",
    tags: ["cardio", "burpees", "hiit"],
    description: "Ejercicio de full body tipo cardio. Requiere peso corporal.",
    clientDescription: "Desde de pie, bajá a posición de plank, hacé una flexión, saltá los pies hacia las manos y terminá con un salto vertical con los brazos arriba. Repetí fluidamente.",
    isPublic: true,
  },
  {
    name: "Escaladores",
    type: "CARDIO" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Peso corporal",
    tags: ["cardio", "escaladores", "hiit"],
    description: "Ejercicio de full body tipo cardio. Requiere peso corporal.",
    clientDescription: "En posición de plank, llevá alternadamente las rodillas hacia el pecho a ritmo rápido como si estuvieras corriendo en el lugar. Mantené la cadera baja y estable.",
    isPublic: true,
  },
  {
    name: "Sprint",
    type: "CARDIO" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Pista",
    tags: ["cardio", "sprint", "running"],
    description: "Ejercicio de piernas tipo cardio. Requiere pista.",
    clientDescription: "Corré a máxima velocidad durante una distancia corta (20-100 metros). Mantené una zancada larga y los brazos impulsando fuerte. Recuperate caminando entre series.",
    isPublic: true,
  },
  {
    name: "Zancadas dinámicas",
    type: "CARDIO" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["cardio", "zancadas", "dinamico"],
    description: "Ejercicio de piernas tipo cardio. Requiere peso corporal.",
    clientDescription: "Dando pasos largos hacia adelante, alterná piernas bajando la rodilla trasera casi hasta el suelo. Mantené el torso erguido y el core activado.",
    isPublic: true,
  },
  {
    name: "Kettlebell swing",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Kettlebell",
    tags: ["kettlebell", "swing", "posterior"],
    description: "Ejercicio de full body tipo functional. Requiere kettlebell.",
    clientDescription: "De pie con los pies más anchos que los hombros, agarrá la kettlebell con ambas manos. Inclinate hacia adelante llevándola entre las piernas y luego extendé las caderas explosivamente para llevarla a la altura del pecho.",
    isPublic: true,
  },
  {
    name: "Turkish get-up",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Kettlebell",
    tags: ["kettlebell", "get up", "movilidad"],
    description: "Ejercicio de full body tipo functional. Requiere kettlebell.",
    clientDescription: "Acostado con una kettlebell extendida sobre el hombro, levantate del suelo pasando por varias posiciones (plancha, rodilla, de pie) sin dejar caer el brazo. Bajá por el mismo camino.",
    isPublic: true,
  },
  {
    name: "Lunges con rotación",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Mancuerna",
    tags: ["lunge", "rotacion", "funcional"],
    description: "Ejercicio de core tipo functional. Requiere mancuerna.",
    clientDescription: "Dá un paso largo hacia adelante en zancada y al bajar, rotá el torso hacia la pierna de adelante. Volvé al centro y alterná piernas.",
    isPublic: true,
  },
  {
    name: "Desplantes laterales",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["desplante", "lateral", "funcional"],
    description: "Ejercicio de piernas tipo functional. Requiere peso corporal.",
    clientDescription: "De pie, dá un paso largo hacia un costado manteniendo la otra pierna recta. Bajá la cadera hacia abajo y empujá para volver. Alterná lados.",
    isPublic: true,
  },
  {
    name: "Thrusters",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Barra",
    tags: ["thrusters", "full body", "crossfit"],
    description: "Ejercicio de full body tipo functional. Requiere barra.",
    clientDescription: "Con la barra en posición de front squat, hacé una sentadilla completa y al subir empujá la barra hacia arriba en un press de hombros. Bajá controladamente.",
    isPublic: true,
  },
  {
    name: "Clean and press",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Barra",
    tags: ["clean", "press", "olimpico"],
    description: "Ejercicio de full body tipo functional. Requiere barra.",
    clientDescription: "Desde el suelo, levantá la barra explosivamente hasta los hombros en posición de front squat (clean) y luego empujá hacia arriba (press). Bajá controladamente.",
    isPublic: true,
  },
  {
    name: "Snatch",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Barra",
    tags: ["snatch", "olimpico", "potencia"],
    description: "Ejercicio de full body tipo functional. Requiere barra.",
    clientDescription: "Levantá la barra del suelo hasta por encima de la cabeza en un solo movimiento explosivo, recibiéndola con los brazos extendidos. Requiere técnica avanzada.",
    isPublic: true,
  },
  {
    name: "Wall ball",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Balón",
    tags: ["wall ball", "crossfit", "full body"],
    description: "Ejercicio de full body tipo functional. Requiere balón.",
    clientDescription: "Con un balón medicinal en el pecho, hacé una sentadilla completa y al subir lanzá el balón hacia arriba contra la pared. Atrapá el balón al bajar y repetí.",
    isPublic: true,
  },
  {
    name: "Box jump",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Cajón",
    tags: ["box jump", "plyometrico", "piernas"],
    description: "Ejercicio de piernas tipo functional. Requiere cajón.",
    clientDescription: "Frente a una caja pliométrica, flexioná ligeramente las rodillas y saltá sobre la caja aterrizando con ambos pies y extendiendo las caderas. Bajá caminando o saltando.",
    isPublic: true,
  },
  {
    name: "Farmer walk",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Mancuernas",
    tags: ["farmer walk", "agarre", "core"],
    description: "Ejercicio de full body tipo functional. Requiere mancuernas.",
    clientDescription: "De pie con mancuernas pesadas en cada mano, caminá manteniendo los hombros hacia atrás, el core apretado y una postura erguida. Recorré una distancia determinada.",
    isPublic: true,
  },
  {
    name: "Sled push",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Trineo",
    tags: ["sled", "empuje", "piernas"],
    description: "Ejercicio de piernas tipo functional. Requiere trineo.",
    clientDescription: "Con las manos en el trineo cargado, empujá con las piernas manteniendo los brazos extendidos y la espalda recta. Empujá el trineo a lo largo de la distancia indicada.",
    isPublic: true,
  },
  {
    name: "Battle ropes",
    type: "FUNCTIONAL" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Cuerdas",
    tags: ["battle ropes", "core", "cardio"],
    description: "Ejercicio de core tipo functional. Requiere cuerdas.",
    clientDescription: "De pie con una cuerda en cada mano, mové los brazos arriba y abajo alternadamente o juntos creando olas en las cuerdas. Mantené el core apretado y las rodillas ligeramente flexionadas.",
    isPublic: true,
  },
  {
    name: "Puentes",
    type: "MOBILITY" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Peso corporal",
    tags: ["puente", "movilidad", "core"],
    description: "Ejercicio de core tipo mobility. Requiere peso corporal.",
    clientDescription: "Acostado boca arriba con las rodillas flexionadas y pies en el suelo, elevá las caderas hacia arriba apretando los glúteos. Mantené la posición unos segundos y bajá.",
    isPublic: true,
  },
  {
    name: "Gato-vaca",
    type: "MOBILITY" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Peso corporal",
    tags: ["gato vaca", "movilidad", "espalda"],
    description: "Ejercicio de espalda tipo mobility. Requiere peso corporal.",
    clientDescription: "A cuatro patas, arqueá la espalda hacia arriba metiendo el ombligo (gato) y luego arqueá hacia abajo mirando hacia arriba (vaca). Movete lentamente entre ambas posiciones.",
    isPublic: true,
  },
  {
    name: "Rotación de cadera",
    type: "MOBILITY" as ExerciseType,
    muscleGroup: "Cadera",
    equipment: "Peso corporal",
    tags: ["rotacion", "cadera", "movilidad"],
    description: "Ejercicio de cadera tipo mobility. Requiere peso corporal.",
    clientDescription: "A cuatro patas, llevá una rodilla hacia adelante y rotá la cadera abriendo la pierna hacia afuera. Volvé al centro y alterná. Sentí el estiramiento en la cadera.",
    isPublic: true,
  },
  {
    name: "Foam rolling",
    type: "MOBILITY" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Foam roller",
    tags: ["foam roller", "movilidad", "recuperacion"],
    description: "Ejercicio de full body tipo mobility. Requiere foam roller.",
    clientDescription: "Acostado sobre el foam roller, ruedá lentamente por la zona muscular que querés liberar. Cuando encontrés un punto doloroso, detenete y mantené la presión unos segundos.",
    isPublic: true,
  },
  {
    name: "Dislocaciones con palo",
    type: "MOBILITY" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Palo",
    tags: ["dislocaciones", "hombros", "movilidad"],
    description: "Ejercicio de hombros tipo mobility. Requiere palo.",
    clientDescription: "De pie con un palo o banda elástica, agarrá con las manos amplias y llevá el palo por encima de la cabeza y detrás de la espalda. Volvé al frente. Ampliá el agarre progresivamente.",
    isPublic: true,
  },
  {
    name: "Movilidad de tobillos",
    type: "MOBILITY" as ExerciseType,
    muscleGroup: "Tobillos",
    equipment: "Peso corporal",
    tags: ["tobillos", "movilidad", "calentamiento"],
    description: "Ejercicio de tobillos tipo mobility. Requiere peso corporal.",
    clientDescription: "De pie frente a una pared, apoyá las manos y llevá una rodilla hacia la pared manteniendo el talón en el suelo. Sentí el estiramiento en el tobillo y la pantorrilla.",
    isPublic: true,
  },
  {
    name: "Thoracic rotation",
    type: "MOBILITY" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Peso corporal",
    tags: ["toracica", "rotacion", "movilidad"],
    description: "Ejercicio de espalda tipo mobility. Requiere peso corporal.",
    clientDescription: "A cuatro patas con una mano detrás de la cabeza, rotá el torso abriendo el codo hacia arriba. Volvé al centro y repetí. Enfoca la rotación de la columna torácica.",
    isPublic: true,
  },
  {
    name: "90/90 stretch",
    type: "MOBILITY" as ExerciseType,
    muscleGroup: "Cadera",
    equipment: "Peso corporal",
    tags: ["90 90", "cadera", "movilidad"],
    description: "Ejercicio de cadera tipo mobility. Requiere peso corporal.",
    clientDescription: "Sentado en el suelo con ambas piernas en ángulo de 90° (una adelante, una atrás), inclinate hacia adelante sobre la pierna delantera. Mantené la espalda recta.",
    isPublic: true,
  },
  {
    name: "Estiramiento de isquiotibiales",
    type: "STRETCHING" as ExerciseType,
    muscleGroup: "Femoral",
    equipment: "Peso corporal",
    tags: ["estiramiento", "isquiotibiales", "flexibilidad"],
    description: "Ejercicio de femoral tipo stretching. Requiere peso corporal.",
    clientDescription: "Sentado con una pierna extendida y la otra flexionada con el pie contra el muslo interno, inclinate hacia adelante intentando tocar los dedos del pie extendido. Mantené la espalda recta.",
    isPublic: true,
  },
  {
    name: "Estiramiento de pectorales",
    type: "STRETCHING" as ExerciseType,
    muscleGroup: "Pecho",
    equipment: "Peso corporal",
    tags: ["estiramiento", "pectorales", "flexibilidad"],
    description: "Ejercicio de pecho tipo stretching. Requiere peso corporal.",
    clientDescription: "De pie junto a una pared o marco de puerta, colocá el antebrazo en la pared con el codo a la altura del hombro. Girá el torso hacia el lado opuesto sentí el estiramiento en el pecho.",
    isPublic: true,
  },
  {
    name: "Estiramiento de cuádriceps",
    type: "STRETCHING" as ExerciseType,
    muscleGroup: "Cuádriceps",
    equipment: "Peso corporal",
    tags: ["estiramiento", "cuadriceps", "flexibilidad"],
    description: "Ejercicio de cuádriceps tipo stretching. Requiere peso corporal.",
    clientDescription: "De pie, agarrá el tobillo con la mano del mismo lado y llevá el talón hacia los glúteos. Mantené las rodillas juntas y el torso erguido.",
    isPublic: true,
  },
  {
    name: "Estiramiento de hombros",
    type: "STRETCHING" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Peso corporal",
    tags: ["estiramiento", "hombros", "flexibilidad"],
    description: "Ejercicio de hombros tipo stretching. Requiere peso corporal.",
    clientDescription: "Llevá un brazo horizontalmente frente al pecho y sujetálo con el otro brazo cerca del codo. Tirá suavemente hacia tu pecho. Mantené el hombro relajado.",
    isPublic: true,
  },
  {
    name: "Estiramiento de pantorrilla",
    type: "STRETCHING" as ExerciseType,
    muscleGroup: "Pantorrilla",
    equipment: "Peso corporal",
    tags: ["estiramiento", "pantorrilla", "flexibilidad"],
    description: "Ejercicio de pantorrilla tipo stretching. Requiere peso corporal.",
    clientDescription: "De pie frente a una pared, dá un paso atrás con una pierna y mantené el talón en el suelo. Inclinate hacia la pared sintiendo el estiramiento en la pantorrilla de atrás.",
    isPublic: true,
  },
  {
    name: "Estiramiento de cadera",
    type: "STRETCHING" as ExerciseType,
    muscleGroup: "Cadera",
    equipment: "Peso corporal",
    tags: ["estiramiento", "cadera", "flexibilidad"],
    description: "Ejercicio de cadera tipo stretching. Requiere peso corporal.",
    clientDescription: "De rodillas, llevá una pierna hacia adelante en ángulo de 90° y estirá la otra hacia atrás. Inclinate hacia adelante sintiendo el estiramiento en la cadera delantera.",
    isPublic: true,
  },
  {
    name: "Estiramiento de espalda",
    type: "STRETCHING" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Peso corporal",
    tags: ["estiramiento", "espalda", "flexibilidad"],
    description: "Ejercicio de espalda tipo stretching. Requiere peso corporal.",
    clientDescription: "Sentado con las piernas extendidas, inclinate hacia adelante intentando tocar los pies. Mantené la espalda lo más recta posible y no fuerces.",
    isPublic: true,
  },
  {
    name: "Mariposa",
    type: "STRETCHING" as ExerciseType,
    muscleGroup: "Cadera",
    equipment: "Peso corporal",
    tags: ["mariposa", "aductores", "flexibilidad"],
    description: "Ejercicio de cadera tipo stretching. Requiere peso corporal.",
    clientDescription: "Sentado en el suelo con las plantas de los pies juntas y las rodillas hacia afuera, agarrá los tobillos y empujá suavemente las rodillas hacia el suelo con los codos.",
    isPublic: true,
  },
  {
    name: "Postura del niño",
    type: "STRETCHING" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Peso corporal",
    tags: ["yoga", "espalda", "relajacion"],
    description: "Ejercicio de espalda tipo stretching. Requiere peso corporal.",
    clientDescription: "Arrodillado con las rodillas separadas y los glúteos sobre los talones, inclinate hacia adelante extendiendo los brazos y apoyando la frente en el suelo. Relajá la espalda completamente.",
    isPublic: true,
  },
  {
    name: "Cobra",
    type: "STRETCHING" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Peso corporal",
    tags: ["yoga", "cobra", "espalda"],
    description: "Ejercicio de espalda tipo stretching. Requiere peso corporal.",
    clientDescription: "Acostado boca abajo con las manos a los costados del pecho, empujá con los brazos elevando el torso del suelo y arqueando la espalda. Mantené las caderas en el suelo.",
    isPublic: true,
  },
  {
    name: "Salto al cajón",
    type: "PLYOMETRIC" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Cajón",
    tags: ["box jump", "plyometrico", "potencia"],
    description: "Ejercicio de piernas tipo plyometric. Requiere cajón.",
    clientDescription: "Frente a una caja pliométrica, flexioná ligeramente las rodillas y saltá sobre la caja aterrizando con ambos pies y extendiendo las caderas. Bajá caminando o saltando suavemente.",
    isPublic: true,
  },
  {
    name: "Salto con peso corporal",
    type: "PLYOMETRIC" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["salto", "plyometrico", "piernas"],
    description: "Ejercicio de piernas tipo plyometric. Requiere peso corporal.",
    clientDescription: "De pie con los pies a la altura de los hombros, flexioná las rodillas y saltá verticalmente lo más alto que puedas. Aterrizá suavemente con las rodillas ligeramente flexionadas y repetí inmediatamente.",
    isPublic: true,
  },
  {
    name: "Lunges saltados",
    type: "PLYOMETRIC" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["lunge", "saltado", "plyometrico"],
    description: "Ejercicio de piernas tipo plyometric. Requiere peso corporal.",
    clientDescription: "En posición de zancada, saltá explosivamente cambiando de pierna en el aire y aterrizá en zancada con la otra pierna adelante. Mantené el torso erguido.",
    isPublic: true,
  },
  {
    name: "Clapping push-ups",
    type: "PLYOMETRIC" as ExerciseType,
    muscleGroup: "Pecho",
    equipment: "Peso corporal",
    tags: ["push up", "aplauso", "plyometrico"],
    description: "Ejercicio de pecho tipo plyometric. Requiere peso corporal.",
    clientDescription: "En posición de flexión, bajá y empujá explosivamente levantando las manos del suelo lo suficiente para aplaudir antes de aterrizar. Requiere fuerza y coordinación.",
    isPublic: true,
  },
  {
    name: "Broad jump",
    type: "PLYOMETRIC" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["salto", "longitud", "plyometrico"],
    description: "Ejercicio de piernas tipo plyometric. Requiere peso corporal.",
    clientDescription: "De pie con los pies a la altura de los hombros, flexioná las rodillas y saltá hacia adelante lo más lejos posible. Aterrizá con ambos pies y mantené el equilibrio.",
    isPublic: true,
  },
  {
    name: "Tuck jump",
    type: "PLYOMETRIC" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["tuck jump", "plyometrico", "piernas"],
    description: "Ejercicio de piernas tipo plyometric. Requiere peso corporal.",
    clientDescription: "De pie, saltá verticalmente llevando las rodillas hacia el pecho. Aterrizá suavemente con las rodillas flexionadas y repetí inmediatamente.",
    isPublic: true,
  },
  {
    name: "Depth jump",
    type: "PLYOMETRIC" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Cajón",
    tags: ["depth jump", "plyometrico", "potencia"],
    description: "Ejercicio de piernas tipo plyometric. Requiere cajón.",
    clientDescription: "Parado sobre una caja, saltá al suelo y al tocar, saltá inmediatamente hacia arriba lo más alto posible. Requiere buena técnica y preparación física.",
    isPublic: true,
  },
  {
    name: "Skater jumps",
    type: "PLYOMETRIC" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["skater", "lateral", "plyometrico"],
    description: "Ejercicio de piernas tipo plyometric. Requiere peso corporal.",
    clientDescription: "De pie, saltá hacia un lado aterrizando sobre una pierna y luego saltá al lado opuesto. Simulá el movimiento de un patinador. Mantené el equilibrio en cada aterrizaje.",
    isPublic: true,
  },
  {
    name: "Sentadilla en bosu",
    type: "BALANCE" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Bosu",
    tags: ["sentadilla", "bosu", "equilibrio"],
    description: "Ejercicio de piernas tipo balance. Requiere bosu.",
    clientDescription: "Parado sobre el bosu (parte redonda hacia arriba), hacé una sentadilla manteniendo el equilibrio. Los pies deben estar separados a la altura de los hombros. Bajá controladamente.",
    isPublic: true,
  },
  {
    name: "Plancha en bosu",
    type: "BALANCE" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Bosu",
    tags: ["plancha", "bosu", "equilibrio"],
    description: "Ejercicio de core tipo balance. Requiere bosu.",
    clientDescription: "En posición de plank con los antebrazos sobre el bosu, mantené el cuerpo en línea recta. El desequilibrio del bosu hace trabajar más el core para estabilizar.",
    isPublic: true,
  },
  {
    name: "Pájaro en bosu",
    type: "BALANCE" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Bosu",
    tags: ["pajaro", "bosu", "equilibrio"],
    description: "Ejercicio de hombros tipo balance. Requiere bosu.",
    clientDescription: "Parado sobre el bosu con una mancuerna en cada mano, inclinate hacia adelante y elevá los brazos lateralmente. El bosu desafía tu equilibrio mientras trabajás los hombros.",
    isPublic: true,
  },
  {
    name: "Single leg deadlift",
    type: "BALANCE" as ExerciseType,
    muscleGroup: "Femoral",
    equipment: "Mancuerna",
    tags: ["single leg", "deadlift", "equilibrio"],
    description: "Ejercicio de femoral tipo balance. Requiere mancuerna.",
    clientDescription: "De pie sobre una pierna con una mancuerna en la mano del mismo lado, inclinate hacia adelante extendiendo la pierna libre hacia atrás. Bajá la mancuerna casi hasta el suelo y volvé.",
    isPublic: true,
  },
  {
    name: "Equilibrio en una pierna",
    type: "BALANCE" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["equilibrio", "una pierna", "propiocepcion"],
    description: "Ejercicio de piernas tipo balance. Requiere peso corporal.",
    clientDescription: "De pie sobre una pierna con la otra flexionada, mantené el equilibrio. Podés cerrar los ojos o agregar movimientos de brazos para aumentar la dificultad.",
    isPublic: true,
  },
  {
    name: "Plancha con fitball",
    type: "BALANCE" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Fitball",
    tags: ["plancha", "fitball", "equilibrio"],
    description: "Ejercicio de core tipo balance. Requiere fitball.",
    clientDescription: "En posición de plank con los pies o las manos sobre el fitball. Mantené el cuerpo estable mientras la pelota se mueve. Trabaja mucho el core.",
    isPublic: true,
  },
  {
    name: "Puente en fitball",
    type: "BALANCE" as ExerciseType,
    muscleGroup: "Glúteos",
    equipment: "Fitball",
    tags: ["puente", "fitball", "equilibrio"],
    description: "Ejercicio de glúteos tipo balance. Requiere fitball.",
    clientDescription: "Acostado boca arriba con los pies sobre el fitball, elevá las caderas apretando los glúteos. Mantené el equilibrio sobre la pelota inestable.",
    isPublic: true,
  },
  {
    name: "Sentadilla con palo",
    type: "TECHNIQUE" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Palo",
    tags: ["sentadilla", "tecnica", "movilidad"],
    description: "Ejercicio de piernas tipo technique. Requiere palo.",
    clientDescription: "Con un palo o PVC sobre los trapecios, practicá el movimiento de sentadilla enfocándote en la técnica: espalda recta, rodillas alineadas con los pies, profundidad controlada.",
    isPublic: true,
  },
  {
    name: "Press con palo",
    type: "TECHNIQUE" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Palo",
    tags: ["press", "tecnica", "hombros"],
    description: "Ejercicio de hombros tipo technique. Requiere palo.",
    clientDescription: "Con un palo o PVC a la altura de los hombros, practicá el movimiento de press militar enfocándote en la trayectoria recta y la estabilidad del core.",
    isPublic: true,
  },
  {
    name: "Peso muerto con palo",
    type: "TECHNIQUE" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Palo",
    tags: ["peso muerto", "tecnica", "movilidad"],
    description: "Ejercicio de espalda tipo technique. Requiere palo.",
    clientDescription: "Con un palo o PVC frente a los muslos, practicá la bisagra de cadera manteniendo la espalda recta y la barra cerca de las piernas. Enfocate en la técnica, no en el peso.",
    isPublic: true,
  },
  {
    name: "Front squat con palo",
    type: "TECHNIQUE" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Palo",
    tags: ["front squat", "tecnica", "rack"],
    description: "Ejercicio de piernas tipo technique. Requiere palo.",
    clientDescription: "Con el palo en posición de front rack (sobre los hombros delante del cuello), practicá la sentadilla manteniendo los codos altos y el torso vertical.",
    isPublic: true,
  },
  {
    name: "Overhead squat con palo",
    type: "TECHNIQUE" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Palo",
    tags: ["overhead squat", "tecnica", "movilidad"],
    description: "Ejercicio de full body tipo technique. Requiere palo.",
    clientDescription: "Con el palo extendido sobre la cabeza, practicá la sentadilla. Requiere mucha movilidad de hombros y tobillos. Mantené los brazos extendidos y la barra sobre el centro de gravedad.",
    isPublic: true,
  },
  {
    name: "Snatch balance con palo",
    type: "TECHNIQUE" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Palo",
    tags: ["snatch balance", "tecnica", "olimpico"],
    description: "Ejercicio de full body tipo technique. Requiere palo.",
    clientDescription: "Con el palo detrás de la cabeza, hacé una sentadilla parcial y al subir empujá el palo hacia arriba recibiéndolo con los brazos extendidos. Practica la recepción del snatch.",
    isPublic: true,
  },
  {
    name: "Clean pull",
    type: "TECHNIQUE" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Barra",
    tags: ["clean pull", "tecnica", "olimpico"],
    description: "Ejercicio de full body tipo technique. Requiere barra.",
    clientDescription: "Desde el suelo, levantá la barra explosivamente hasta la altura del pecho sin recibirla. Enfocate en la extensión de caderas y la tracción vertical.",
    isPublic: true,
  },
  {
    name: "Snatch pull",
    type: "TECHNIQUE" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Barra",
    tags: ["snatch pull", "tecnica", "olimpico"],
    description: "Ejercicio de full body tipo technique. Requiere barra.",
    clientDescription: "Desde el suelo, levantá la barra explosivamente hasta la altura del pecho con un agarre ancho, sin recibirla por encima de la cabeza. Trabaja la extensión y la tracción.",
    isPublic: true,
  },
  {
    name: "Jumping jacks",
    type: "WARMUP" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Peso corporal",
    tags: ["jumping jacks", "calentamiento", "cardio"],
    description: "Ejercicio de full body tipo warmup. Requiere peso corporal.",
    clientDescription: "De pie, saltá abriendo las piernas y levantando los brazos lateralmente por encima de la cabeza. Volvé al centro. Mantené un ritmo constante para elevar la frecuencia cardíaca.",
    isPublic: true,
  },
  {
    name: "Skipping",
    type: "WARMUP" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["skipping", "calentamiento", "pies"],
    description: "Ejercicio de piernas tipo warmup. Requiere peso corporal.",
    clientDescription: "Saltando en el lugar, llevá las rodillas alternadamente hacia arriba mientras movés los brazos como si corrieras. Mantené un ritmo ligero y los pies ágiles.",
    isPublic: true,
  },
  {
    name: "Arm circles",
    type: "WARMUP" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Peso corporal",
    tags: ["arm circles", "calentamiento", "hombros"],
    description: "Ejercicio de hombros tipo warmup. Requiere peso corporal.",
    clientDescription: "De pie con los brazos extendidos lateralmente, hacé círculos pequeños hacia adelante y luego hacia atrás. Progresivamente aumentá el tamaño de los círculos.",
    isPublic: true,
  },
  {
    name: "Leg swings",
    type: "WARMUP" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["leg swings", "calentamiento", "cadera"],
    description: "Ejercicio de piernas tipo warmup. Requiere peso corporal.",
    clientDescription: "Apoyado en una pared o barra, balanceá una pierna hacia adelante y atrás como un péndulo. Mantené el torso estable. Alterná piernas.",
    isPublic: true,
  },
  {
    name: "Trotar en el lugar",
    type: "WARMUP" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["trotar", "calentamiento", "cardio"],
    description: "Ejercicio de piernas tipo warmup. Requiere peso corporal.",
    clientDescription: "Trotando en el lugar, levantá las rodillas moderadamente y balanceá los brazos naturalmente. Mantené un ritmo cómodo para elevar la temperatura corporal.",
    isPublic: true,
  },
  {
    name: "Rotaciones de cuello",
    type: "WARMUP" as ExerciseType,
    muscleGroup: "Cuello",
    equipment: "Peso corporal",
    tags: ["cuello", "calentamiento", "movilidad"],
    description: "Ejercicio de cuello tipo warmup. Requiere peso corporal.",
    clientDescription: "De pie con la espalda recta, rotá la cabeza lentamente hacia un lado, atrás, el otro lado y al frente. Hacelo suavemente sin forzar. Repetí en ambas direcciones.",
    isPublic: true,
  },
  {
    name: "Rotaciones de muñecas",
    type: "WARMUP" as ExerciseType,
    muscleGroup: "Antebrazos",
    equipment: "Peso corporal",
    tags: ["munecas", "calentamiento", "movilidad"],
    description: "Ejercicio de antebrazos tipo warmup. Requiere peso corporal.",
    clientDescription: "Con los brazos extendidos, hacé círculos con las muñecas hacia adentro y hacia afuera. También flexioná y extendé las muñecas para calentar las articulaciones.",
    isPublic: true,
  },
  {
    name: "Caminata de oso",
    type: "WARMUP" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Peso corporal",
    tags: ["oso", "caminata", "calentamiento"],
    description: "Ejercicio de full body tipo warmup. Requiere peso corporal.",
    clientDescription: "Desde plank, llevá las manos hacia adelante un paso y luego los pies hacia las manos manteniendo las piernas rectas. Caminá así por el espacio disponible.",
    isPublic: true,
  },
  {
    name: "Inchworm",
    type: "WARMUP" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Peso corporal",
    tags: ["inchworm", "calentamiento", "flexibilidad"],
    description: "Ejercicio de full body tipo warmup. Requiere peso corporal.",
    clientDescription: "De pie, inclinate hacia adelante y caminá con las manos hasta plank. Hacé una flexión opcional y caminá con las manos de vuelta hacia los pies. Levántate y repetí.",
    isPublic: true,
  },
  {
    name: "High knees",
    type: "WARMUP" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["high knees", "calentamiento", "cardio"],
    description: "Ejercicio de piernas tipo warmup. Requiere peso corporal.",
    clientDescription: "Corriendo en el lugar, llevá las rodillas lo más alto posible alternando rápidamente. Balanceá los brazos en sincronía. Mantené el ritmo y la postura erguida.",
    isPublic: true,
  },
  {
    name: "Caminata lenta",
    type: "COOLDOWN" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Peso corporal",
    tags: ["caminata", "vuelta a la calma", "cardio"],
    description: "Ejercicio de full body tipo cooldown. Requiere peso corporal.",
    clientDescription: "Caminá lentamente por el espacio durante 3-5 minutos. Permití que la frecuencia cardíaca baje gradualmente. Respirá profundamente y relajá los hombros.",
    isPublic: true,
  },
  {
    name: "Respiración diafragmática",
    type: "COOLDOWN" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Peso corporal",
    tags: ["respiracion", "relajacion", "vuelta a la calma"],
    description: "Ejercicio de core tipo cooldown. Requiere peso corporal.",
    clientDescription: "Acostado boca arriba con una mano sobre el pecho y otra sobre el abdomen, inhalá profundamente expandiendo el abdomen (no el pecho). Exhalá lentamente. Repetí 10 veces.",
    isPublic: true,
  },
  {
    name: "Estiramiento de espalda",
    type: "COOLDOWN" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Peso corporal",
    tags: ["estiramiento", "espalda", "vuelta a la calma"],
    description: "Ejercicio de espalda tipo cooldown. Requiere peso corporal.",
    clientDescription: "De rodillas, sentate sobre los talones y extendé los brazos hacia adelante apoyando las manos en el suelo. Dejá caer la frente y relajá la espalda completamente.",
    isPublic: true,
  },
  {
    name: "Estiramiento de hombros",
    type: "COOLDOWN" as ExerciseType,
    muscleGroup: "Hombros",
    equipment: "Peso corporal",
    tags: ["estiramiento", "hombros", "vuelta a la calma"],
    description: "Ejercicio de hombros tipo cooldown. Requiere peso corporal.",
    clientDescription: "Llevá un brazo horizontalmente frente al pecho y sujetálo con el otro brazo. Mantené el estiramiento 20-30 segundos. Relajá los hombros.",
    isPublic: true,
  },
  {
    name: "Estiramiento de piernas",
    type: "COOLDOWN" as ExerciseType,
    muscleGroup: "Piernas",
    equipment: "Peso corporal",
    tags: ["estiramiento", "piernas", "vuelta a la calma"],
    description: "Ejercicio de piernas tipo cooldown. Requiere peso corporal.",
    clientDescription: "Sentado con las piernas extendidas, inclinate hacia adelante suavemente. No fuerces, solo sentí el estiramiento en los isquiotibiales y la espalda baja.",
    isPublic: true,
  },
  {
    name: "Foam roller de espalda",
    type: "COOLDOWN" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Foam roller",
    tags: ["foam roller", "espalda", "recuperacion"],
    description: "Ejercicio de espalda tipo cooldown. Requiere foam roller.",
    clientDescription: "Acostado sobre el foam roller con éste a la altura de la espalda baja, ruedá lentamente hacia arriba y abajo por toda la espalda. Detenete en puntos tensos.",
    isPublic: true,
  },
  {
    name: "Shavasana",
    type: "COOLDOWN" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Peso corporal",
    tags: ["shavasana", "relajacion", "vuelta a la calma"],
    description: "Ejercicio de full body tipo cooldown. Requiere peso corporal.",
    clientDescription: "Acostado boca arriba con los brazos a los costados y las palmas hacia arriba, relajá completamente todo el cuerpo. Cerrá los ojos y enfocate en la respiración durante 3-5 minutos.",
    isPublic: true,
  },
  {
    name: "Meditación",
    type: "COOLDOWN" as ExerciseType,
    muscleGroup: "Mental",
    equipment: "Peso corporal",
    tags: ["meditacion", "relajacion", "vuelta a la calma"],
    description: "Ejercicio de mental tipo cooldown. Requiere peso corporal.",
    clientDescription: "Sentado cómodamente con la espalda recta, cerrá los ojos y enfocate en tu respiración. Dejá pasar los pensamientos sin aferrarte a ellos. 3-5 minutos.",
    isPublic: true,
  },
  {
    name: "Vacío abdominal",
    type: "OTHER" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Peso corporal",
    tags: ["vacio abdominal", "core", "transverso"],
    description: "Ejercicio de core tipo other. Requiere peso corporal.",
    clientDescription: "De pie o a cuatro patas, exhalá todo el aire y contraé el abdomen hacia adentro como si quisieras tocar la columna con el ombligo. Mantené 10-20 segundos. Respirá normalmente.",
    isPublic: true,
  },
  {
    name: "Kegel",
    type: "OTHER" as ExerciseType,
    muscleGroup: "Piso pélvico",
    equipment: "Peso corporal",
    tags: ["kegel", "piso pelvico", "rehabilitacion"],
    description: "Ejercicio de piso pélvico tipo other. Requiere peso corporal.",
    clientDescription: "Contraé los músculos del piso pélvico (como si retuvieras la orina). Mantené la contracción 5-10 segundos y relajá. No contraigas glúteos ni abdomen.",
    isPublic: true,
  },
  {
    name: "Respiración costal",
    type: "OTHER" as ExerciseType,
    muscleGroup: "Core",
    equipment: "Peso corporal",
    tags: ["respiracion", "costal", "core"],
    description: "Ejercicio de core tipo other. Requiere peso corporal.",
    clientDescription: "Acostado con una mano sobre el pecho y otra sobre las costillas, inhalá expandiendo las costillas lateralmente. Exhalá contrayendo las costillas. No muevas el abdomen.",
    isPublic: true,
  },
  {
    name: "Activación glútea",
    type: "OTHER" as ExerciseType,
    muscleGroup: "Glúteos",
    equipment: "Banda",
    tags: ["activacion", "gluteos", "prehab"],
    description: "Ejercicio de glúteos tipo other. Requiere banda.",
    clientDescription: "Acostado boca arriba con las rodillas flexionadas y una banda elástica sobre las rodillas, separá las rodillas contra la resistencia de la banda apretando los glúteos.",
    isPublic: true,
  },
  {
    name: "Activación de escápulas",
    type: "OTHER" as ExerciseType,
    muscleGroup: "Espalda",
    equipment: "Peso corporal",
    tags: ["activacion", "escapulas", "postura"],
    description: "Ejercicio de espalda tipo other. Requiere peso corporal.",
    clientDescription: "De pie o acostado boca arriba, empujá los omóplatos hacia abajo y juntos (retracción) sin mover los brazos. Mantené 5 segundos y relajá. Enfoca la conexión mente-músculo.",
    isPublic: true,
  },
  {
    name: "Masaje con pelota",
    type: "OTHER" as ExerciseType,
    muscleGroup: "Full body",
    equipment: "Pelota",
    tags: ["masaje", "automasaje", "recuperacion"],
    description: "Ejercicio de full body tipo other. Requiere pelota.",
    clientDescription: "Con una pelota de lacrosse o tenis, apoyala sobre el músculo tensos y movete lentamente sobre ella. Cuando encontrés un punto doloroso, mantené la presión 30-60 segundos.",
    isPublic: true,
  },
]

async function main() {
  console.log(`🌱 Iniciando seed de ejercicios...`)
  console.log(`📊 Total de ejercicios a cargar: ${exercises.length}`)

  let created = 0
  let updated = 0
  let skipped = 0

  for (const exercise of exercises) {
    const existing = await prisma.exercise.findFirst({
      where: { name: exercise.name }
    })

    if (!existing) {
      await prisma.exercise.create({
        data: {
          name: exercise.name,
          type: exercise.type,
          description: exercise.description,
          clientDescription: exercise.clientDescription,
          muscleGroup: exercise.muscleGroup,
          equipment: exercise.equipment,
          tags: exercise.tags,
          isPublic: exercise.isPublic,
        }
      })
      created++
      console.log(`✅ Creado: ${exercise.name} (${exercise.type})`)
    } else {
      // Actualizar si ya existe (para agregar campos nuevos como clientDescription)
      await prisma.exercise.update({
        where: { id: existing.id },
        data: {
          description: exercise.description ?? existing.description,
          clientDescription: exercise.clientDescription ?? existing.clientDescription,
          muscleGroup: exercise.muscleGroup ?? existing.muscleGroup,
          equipment: exercise.equipment ?? existing.equipment,
          tags: exercise.tags ?? existing.tags,
        }
      })
      updated++
      console.log(`🔄 Actualizado: ${exercise.name}`)
    }
  }

  const totalInDb = await prisma.exercise.count()
  console.log(`\n🎉 Seed completado!`)
  console.log(`   Creados: ${created}`)
  console.log(`   Actualizados: ${updated}`)
  console.log(`   Total en base de datos: ${totalInDb}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })